Fix build yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,6 +9,22 @@ jobs:
   sonarcloud:
     name: SonarCloud
     runs-on: ubuntu-latest
+
+    services:
+      mysql:
+        image: mysql:5.7
+        env:
+          MYSQL_ALLOW_EMPTY_PASSWORD: false
+          MYSQL_ROOT_PASSWORD: symfony
+          MYSQL_DATABASE: symfony
+        ports:
+          - 3306/tcp
+        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
+      strategy:
+        fail-fast: false
+        matrix:
+          php-versions: [ '7.3', '7.4' ]
+
     steps:
       - uses: actions/checkout@v2
         with:
@@ -21,7 +37,8 @@ jobs:
           extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
           tools: composer:v2
           coverage: pcov
-
+      - name: Start mysql service
+          run: sudo /etc/init.d/mysql start
       - name: Get composer cache directory
         id: composer-cache
         run: echo "::set-output name=dir::$(composer config cache-files-dir)"
@@ -33,9 +50,18 @@ jobs:
           key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
           restore-keys: ${{ runner.os }}-composer-
 
-      - name: Install dependencies
-        run: composer install --prefer-dist
+      - name: Install Composer dependencies
+          run: |
+            composer require --dev symfony/orm-pack symfony/phpunit-bridge
+            composer install --no-progress --prefer-dist --optimize-autoloader
+            php bin/phpunit install
 
+      - name: Run Migration
+          run: |
+            php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
+            php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+          env:
+            DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
       - name: Execute tests
         run: ./vendor/bin/simple-phpunit --bootstrap tests/bootstrap.php --configuration phpunit.xml.dist --coverage-clover coverage.xml --log-junit junit.xml
       - name: fix code coverage paths
